// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for suggesting event layouts and decor options based on user input.
 *
 * - suggestEventLayout - An async function that takes event details and user preferences as input and returns layout and decor suggestions.
 * - SuggestEventLayoutInput - The input type for the suggestEventLayout function.
 * - SuggestEventLayoutOutput - The return type for the suggestEventLayout function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestEventLayoutInputSchema = z.object({
  numberOfGuests: z
    .number()
    .describe('The number of guests attending the event.'),
  eventType: z.string().describe('The type of event (e.g., wedding, corporate meeting, quinceañera).'),
  userPreferences: z
    .string()
    .describe('A description of the user\u2019s preferences for the event, including style, color schemes, and ambiance.'),
});
export type SuggestEventLayoutInput = z.infer<typeof SuggestEventLayoutInputSchema>;

const SuggestEventLayoutOutputSchema = z.object({
  layoutSuggestion: z
    .string()
    .describe('A detailed suggestion for the event layout, including table arrangements, stage setup, and seating.'),
  decorSuggestions: z
    .string()
    .describe('Suggestions for decor options, including color schemes, floral arrangements, lighting, and table settings.'),
});
export type SuggestEventLayoutOutput = z.infer<typeof SuggestEventLayoutOutputSchema>;

export async function suggestEventLayout(input: SuggestEventLayoutInput): Promise<SuggestEventLayoutOutput> {
  return suggestEventLayoutFlow(input);
}

const suggestEventLayoutPrompt = ai.definePrompt({
  name: 'suggestEventLayoutPrompt',
  input: {schema: SuggestEventLayoutInputSchema},
  output: {schema: SuggestEventLayoutOutputSchema},
  prompt: `You are an AI event planning assistant. Your goal is to suggest the optimal layout and decor for events, incorporating the event details and user preferences into the suggestion. 

Based on the following information, suggest an event layout and decor options:

Number of Guests: {{{numberOfGuests}}}
Event Type: {{{eventType}}}
User Preferences: {{{userPreferences}}}

Consider practical aspects such as traffic flow, stage visibility, and accessibility, along with aesthetic elements to create a memorable and visually appealing event.

Your suggestions should include:
- A detailed layout suggestion, including table arrangements, stage setup and seating.
- Decor suggestions, including color schemes, floral arrangements, lighting and table settings.
`,
});

const suggestEventLayoutFlow = ai.defineFlow(
  {
    name: 'suggestEventLayoutFlow',
    inputSchema: SuggestEventLayoutInputSchema,
    outputSchema: SuggestEventLayoutOutputSchema,
  },
  async input => {
    const {output} = await suggestEventLayoutPrompt(input);
    return output!;
  }
);
